services:
  nodejs-server:
    image: divyanshugahlot0318/chaicode-node
    deploy:
      replicas: 5
    networks:
      - chaicode-internal


  caddy:
    image: caddy:latest
    ports:
      - '80:80'
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - chaicode-internal

networks:
  chaicode-internal:
    driver: bridge
      