name: Deploy Nodejs code on excloud

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

          - name: Checkout code 
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v4
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v4

          - name: Build and push
            run: |
              docker build -t divyanshugahlot0318/chaicode-node .
              docker push divyanshugahlot0318/chaicode-node

          - name: deploy on ExCloud
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: "210.79.128.201"
                port: 22
                username: ubuntu
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                  #Kill the existing container 
                  sudo docker rm chaicode-node || true

                  #again pull the fresh image 
                  sudo docker pull divyanshugahlot0318/chaicode-node

                  #Run docker run -d -p 3000:3000 divyanshugahlot0318/chaicode-node

                  sudo docker run -d --name chaicode-node --restart unless-stopped 3000:3000 divyanshugahlot0318/chaicode-node

                  #cleanup all unused image 
                  sudo docker image prune -f